### ISSUE TITLE
Start of SplashFOAM

### ISSUE THREAD

**Issue by Formula78** [mohamedalysayed/SplashFOAM#154]
Hi, 
First thank you for the GUI!
I can't start SplashFOAM in the current Standard-release branch. I installed all necessary packages, but starting the programme with "python3 SplashFOAM.py" appears: 

        Traceback (most recent call last):
          File "/SplashFOAM/Source/SplashFOAM.py", line 2132, in <module>
            root = tk.Tk()
          File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
            self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
        _tkinter.TclError: couldn't connect to display "localhost:0"

Do you have any solution for this problem?

**Comment by mohamedalysayed** [comment]
Hi @Formula78 

Thanks for the feedback! Seems your x11 is not set properly. Please try the instructions in [**this post**](https://stackoverflow.com/questions/49169055/docker-tkinter-tclerror-couldnt-connect-to-display/49229627#49229627) and let me know if it fixes the issue.

**Comment by rodneybalzar** [comment]
the command "export DISPLAY=:0" fixed it for me
